name: Main
on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    name: build and test
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Select xcode version
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: check xcode version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild build-for-testing CODE_SIGNING_ALLOWED=NO -scheme "GithubCICD" -destination "platform=iOS Simulator,name=iPhone 14"
      - name: Test
        run: xcodebuild test-without-building -scheme "GithubCICD" -destination "platform=iOS Simulator,name=iPhone 14"
